/** IG-006 — cross-device execution attestation composition. Fresh post-V2-016 proof; PR #152 remains historical and untouched. */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { createHash } from 'node:crypto';
import { buildServer } from '../../../src/api/server.js';
import { ApiKeyAuthProvider } from '../../../src/modules/auth/internal/api-key-auth-provider.js';
import { ApiKeyCredentialProvisioner } from '../../../src/modules/auth/internal/authorization-service.js';
import { EnvSecretStore, InMemoryQueue } from '@platform/index.js';
import { createLogger } from '@platform/logger.js';
import { buildTriggerTestStack, versionContentOf, TRIGGER_TEST_EPOCH, type TriggerTestStack } from '../workflow-deployments/trigger-test-support.js';
import { ComputerAgentRuntime, WebBrowserHostAdapter, DesktopHostAdapter, ScriptedBrowserEnvironment, ScriptedDesktopEnvironment, registerComputerHost, type AgentDecider, type AttestingComputerHost, type ComputerAgentPolicy, type ComputerHostAdapter, type DependentStepPrecondition } from '../../../src/computer-agent/index.js';
import { generateAttesterKeyPair, verifyAttestation, serializeAttestation, parseAttestation, InMemoryReplayRegistry, InMemoryAttestationLedger, type AttesterKeyPair } from '../../../src/execution-attestation/index.js';
import { createWorkflowIrBuilder, computeWorkflowVersionSemanticDigest, parseWorkflowIrDocument, type WorkflowIrDocument, type WorkflowNode } from '../../../src/workflow-ir/index.js';
import type { FastifyInstance } from 'fastify';

const API_KEY = 'ig-006-api-test-key';
const EXTERNAL_ID = 'v2-009-owner-a';
const FORM_URL = 'https://integration.example/intake';
const ACK_PATH = 'reports/ack.md';
const ACK_CONTENT = 'ACK: intake form submitted and attested across devices';
const BROWSER_CAPS = [
  { name: 'browser.observe', version: 1, availability: 'available' as const },
  { name: 'browser.click', version: 1, availability: 'available' as const },
];
const FILE_CAPS = [
  { name: 'filesystem.read', version: 1, availability: 'available' as const },
  { name: 'filesystem.write', version: 1, availability: 'available' as const },
];
let support: TriggerTestStack;
let app: FastifyInstance;
let principal: { userId: string };
let organizationId: string;

const sha256 = (s: string) => createHash('sha256').update(s, 'utf8').digest('hex');

function document(): WorkflowIrDocument {
  const collect: WorkflowNode = { id:'collect', executionClass:'agentic_computer_use', spec:{class:'agentic_computer_use',task:'Submit intake form'}, capabilityRequirements:['browser.observe','browser.click'], placement:'cloud_allowed', inputs:[{name:'formUrl',type:{kind:'string'},binding:{kind:'workflow_input',input:'formUrl'}}], outputs:[{name:'submitted',type:{kind:'boolean'}}], failurePolicy:{strategy:'fail_workflow'}, completionEvidence:'observation' };
  const approve: WorkflowNode = { id:'approve', executionClass:'human', spec:{class:'human',human:{kind:'approval',instruction:'Approve handoff'}}, capabilityRequirements:[], placement:'device_local', inputs:[], outputs:[{name:'approved',type:{kind:'boolean'}}], failurePolicy:{strategy:'fail_workflow'}, completionEvidence:'human_confirmation' };
  const record: WorkflowNode = { id:'record_ack', executionClass:'agentic_computer_use', spec:{class:'agentic_computer_use',task:'Write acknowledgement'}, capabilityRequirements:['filesystem.read','filesystem.write'], placement:'device_local', inputs:[{name:'ackPath',type:{kind:'string'},binding:{kind:'literal',value:ACK_PATH}},{name:'ackContent',type:{kind:'string'},binding:{kind:'literal',value:ACK_CONTENT}}], outputs:[{name:'written',type:{kind:'boolean'}}], failurePolicy:{strategy:'fail_workflow'}, completionEvidence:'observation' };
  return createWorkflowIrBuilder().withStart('collect').addWorkflowInput({name:'formUrl',type:{kind:'string'}}).addNode(collect).addNode(approve).addNode(record)
    .addEdge({from:'collect',to:'approve',on:'success'}).addEdge({from:'approve',to:'record_ack',on:{outcome:'approved'}}).build();
}
function localDocument(): WorkflowIrDocument {
  return createWorkflowIrBuilder().withStart('record_ack').addNode({id:'record_ack',executionClass:'agentic_computer_use',spec:{class:'agentic_computer_use',task:'Write acknowledgement'},capabilityRequirements:['filesystem.read','filesystem.write'],placement:'device_local',inputs:[{name:'ackPath',type:{kind:'string'},binding:{kind:'literal',value:ACK_PATH}},{name:'ackContent',type:{kind:'string'},binding:{kind:'literal',value:ACK_CONTENT}}],outputs:[{name:'written',type:{kind:'boolean'}}],failurePolicy:{strategy:'fail_workflow'},completionEvidence:'observation'}).build();
}

class Capture implements AttestingComputerHost {
  readonly nodeId:string; readonly sessionToken:string; readonly platformClass:AttestingComputerHost['platformClass']; readonly capabilities:ComputerHostAdapter['capabilities']; readonly attestationSupport:{readonly supported:true;readonly attesterKeyId:string};
  private readonly host:AttestingComputerHost; readonly attestations:ReturnType<AttestingComputerHost['signStatement']>[]=[];
  constructor(host:ComputerHostAdapter){if(!host.attestationSupport.supported)throw new Error('attester required');this.host=host as AttestingComputerHost;this.nodeId=host.nodeId;this.sessionToken=host.sessionToken;this.platformClass=host.platformClass;this.capabilities=host.capabilities;this.attestationSupport=this.host.attestationSupport;}
  invoke(...args:Parameters<ComputerHostAdapter['invoke']>){return this.host.invoke(...args)} nextNonce(){return this.host.nextNonce()} signStatement(...args:Parameters<AttestingComputerHost['signStatement']>){const a=this.host.signStatement(...args);this.attestations.push(a);return a;}
}
function browserDecider():AgentDecider{return c=>{if(!c.observation)return{decision:'observe',capability:'browser.observe',subject:FORM_URL};if(!c.history.some(r=>r.capability==='browser.click'&&r.ok)){const t=c.observation.elements.find(e=>e.elementId==='btn-submit');return{decision:'act',capability:'browser.click',grounding:t?{observationId:c.observation.observationId,targetElementId:t.elementId,targetDigest:t.digest}:null,parameters:{}};}return{decision:'complete',verify:{capability:'browser.observe',subject:FORM_URL,expect:{elementId:'btn-submit',state:'clicked'}},outputs:{submitted:true}};};}
function ackDecider():AgentDecider{return c=>{if(!c.observation)return{decision:'observe',capability:'filesystem.read',subject:ACK_PATH};if(!c.history.some(r=>r.capability==='filesystem.write'&&r.ok)){const t=c.observation.elements.find(e=>e.elementId===ACK_PATH);return{decision:'act',capability:'filesystem.write',grounding:t?{observationId:c.observation.observationId,targetElementId:t.elementId,targetDigest:t.digest}:null,parameters:{path:ACK_PATH,content:ACK_CONTENT}};}return{decision:'complete',verify:{capability:'filesystem.read',subject:ACK_PATH,expect:{elementId:ACK_PATH,state:ACK_CONTENT}},outputs:{written:true}};};}
function runtime(nodes:TriggerTestStack['nodes'],attestation:ComputerAgentPolicy['attestation'],dependentStepIds:readonly string[]=[]){return new ComputerAgentRuntime({recorder:support.runs,nodes,workflowRepository:support.repository,clock:()=>support.clock.utc(),epoch:TRIGGER_TEST_EPOCH,policy:{maxActionsPerStep:12,maxObservationAgeMs:60000,maxRecoveryCyclesPerStep:4,safeAction:{grants:[{capability:'browser.observe',scope:'run'},{capability:'browser.click',scope:'run'},{capability:'filesystem.read',scope:'run'},{capability:'filesystem.write',scope:'run'}]},attestation,dependentStepIds},replayRegistry:new InMemoryReplayRegistry()});}
async function inject(method:'GET'|'POST',url:string,payload?:unknown){const r=await app.inject({method,url,headers:payload===undefined?{authorization:`Bearer ${API_KEY}`}:{authorization:`Bearer ${API_KEY}`,'content-type':'application/json'},payload:payload as Record<string,unknown>|undefined});return{status:r.statusCode,body:(r.json()??{}) as Record<string,unknown>,raw:r.body};}
async function createRun(workflowId:string,versionId:string,id:string){const x=await support.runs.requestRun(principal,{commandId:`cmd-${id}`,correlationId:`corr-${id}`},{organizationId,workflowId,versionId,trigger:{type:'manual',id},inputCommitments:[sha256(id)]});return x.result.run;}

beforeAll(async()=>{support=await buildTriggerTestStack({WFOS_IG_006_API_TEST_KEY:API_KEY});const owner=await support.stack.userRepository.findById(support.ownerAId);if(!owner)throw new Error('owner missing');principal={userId:owner.id};organizationId=support.orgAId;await support.stack.membershipRepository.assign({userId:owner.id,organizationId,roleId:'owner'});const p=new ApiKeyCredentialProvisioner(support.stack.db.client);await p.provision({keyId:'ig6-api-key',secretRef:'WFOS_IG_006_API_TEST_KEY',externalId:EXTERNAL_ID,label:'IG-006 API',rawKey:API_KEY});const auth=new ApiKeyAuthProvider(support.stack.db.client,new EnvSecretStore());app=await buildServer({queue:new InMemoryQueue(),logger:createLogger({level:'silent'}),auth:{authProvider:auth,userRepository:support.stack.userRepository},workflowRepository:{workflowRepositoryService:support.repository},workflowRuns:{workflowRunService:support.runs},workflowDeployments:{workflowDeploymentService:support.deployments}});await app.ready();});
afterAll(async()=>{await app.close();await support.teardown();});

describe('IG-006 re-proof after V2-016',()=>{
 it('proves the real two-node path and all composition boundaries',async()=>{
  const nodes=support.nodes,keyA=generateAttesterKeyPair(),keyB=generateAttesterKeyPair();
  const browser=new ScriptedBrowserEnvironment([{url:FORM_URL,elements:[{elementId:'btn-submit',kind:'button',label:'Submit',state:'enabled'}]}]);
  const desktop=new ScriptedDesktopEnvironment({directories:['reports']});
  const ra=registerComputerHost({nodes,keySeed:'ig6-a',platformClass:'web',capabilities:BROWSER_CAPS});
  const rb=registerComputerHost({nodes,keySeed:'ig6-b',platformClass:'desktop',capabilities:FILE_CAPS});
  const hostA=new Capture(new WebBrowserHostAdapter({nodeId:ra.nodeId,sessionToken:ra.sessionToken,clock:()=>support.clock.utc(),capabilities:BROWSER_CAPS,attestation:{supported:true,attesterKeyId:keyA.keyId},attesterKey:keyA,environment:browser}));
  const hostB=new Capture(new DesktopHostAdapter({nodeId:rb.nodeId,sessionToken:rb.sessionToken,clock:()=>support.clock.utc(),capabilities:FILE_CAPS,attestation:{supported:true,attesterKeyId:keyB.keyId},attesterKey:keyB,environment:desktop}));
  const created=await (async()=>{const r=await inject('POST',`/organizations/${organizationId}/workflow-repository/workflows`,{slug:'ig6-reproof',name:'IG6',description:'cross-device',visibility:'private',content:versionContentOf(document()),protocol:{irSchemaVersion:'workflowos-workflow-ir-v1'}});expect(r.status,r.raw).toBe(201);return r.body as unknown as {workflow:{id:string};initialVersion:{id:string;versionNumber:number;contentDigest:string}}})();
  const ins=await inject('POST',`/organizations/${organizationId}/workflow-repository/installations`,{workflowId:created.workflow.id,versionId:created.initialVersion.id});expect(ins.status,ins.raw).toBe(201);const installation=(ins.body as unknown as {installation:{id:string}}).installation;
  const vr=await inject('GET',`/workflow-repository/workflows/${created.workflow.id}/versions/${created.initialVersion.id}`);expect(vr.status).toBe(200);const pp=parseWorkflowIrDocument(JSON.stringify((vr.body as unknown as {version:{content:Record<string,unknown>}}).version.content));expect(pp.ok).toBe(true);if(!pp.ok)throw new Error('parse failed');const semantic=computeWorkflowVersionSemanticDigest(pp.document).digest;
  const dep=await support.deployments.createDeployment(principal,{organizationId,workflowId:created.workflow.id,versionId:created.initialVersion.id,installationId:installation.id,name:'ig6-dep',placement:{placement:{required:'cloud_allowed'},privacy:{localOnly:false}}});await support.deployments.createSubscription(principal,{deploymentId:dep.deployment.id,kind:'event',eventPattern:{eventType:'file.changed'}});
  const run=await createRun(created.workflow.id,created.initialVersion.id,'ig6-main');
  const reportA=await runtime(nodes,{required:true,trustedAttesterKeyIds:[keyA.keyId],validityMs:300000}).executeRun(principal,{runId:run.id,hosts:[hostA],decider:browserDecider(),workflowInputs:{formUrl:FORM_URL}});expect(reportA.state).toBe('paused');
  const histA=await support.runs.getRunHistory(principal,run.id);const a=histA.attestations.find(b=>b.stepId==='collect')!;const attA=hostA.attestations[0]!;
  const bytes=serializeAttestation(attA),parsedAtt=parseAttestation(bytes);expect(parsedAtt.ok).toBe(true);if(!parsedAtt.ok)throw new Error('transfer parse failed');
  const replayRegistry=new InMemoryReplayRegistry();const verified=verifyAttestation(parsedAtt.attestation,{bindings:{workflowId:created.workflow.id,workflowVersionId:created.initialVersion.id,workflowVersionSemanticDigest:semantic,deploymentId:installation.id,runId:run.id,attemptId:1,stepId:'collect'},freshness:{now:support.clock.utc(),currentEpoch:TRIGGER_TEST_EPOCH,replayRegistry},attesterKeyIds:[keyA.keyId]});expect(verified.ok).toBe(true);if(!verified.ok)throw new Error('verification failed');const fact=verified.fact;
  const replay=verifyAttestation(parsedAtt.attestation,{bindings:{runId:run.id},freshness:{now:support.clock.utc(),currentEpoch:TRIGGER_TEST_EPOCH,replayRegistry},attesterKeyIds:[keyA.keyId]});expect(replay.ok).toBe(false);if(!replay.ok)expect(replay.failure.code).toBe('ATTESTATION_REPLAYED');
  const stale=verifyAttestation(parsedAtt.attestation,{bindings:{runId:run.id},freshness:{now:support.clock.utc(),currentEpoch:TRIGGER_TEST_EPOCH+1,replayRegistry:new InMemoryReplayRegistry()}});expect(stale.ok).toBe(false);if(!stale.ok)expect(stale.failure.code).toBe('ATTESTATION_EPOCH_STALE');
  const expired=verifyAttestation(parsedAtt.attestation,{bindings:{runId:run.id},freshness:{now:'2100-01-01T00:00:00.000Z',currentEpoch:TRIGGER_TEST_EPOCH,replayRegistry:new InMemoryReplayRegistry()}});expect(expired.ok).toBe(false);if(!expired.ok)expect(expired.failure.code).toBe('ATTESTATION_EXPIRED');
  const pre:DependentStepPrecondition={dependentStepId:'record_ack',predecessorAttestationId:fact.attestationId,verifiedPredecessor:fact,causalParentDigests:[a.executionDigest],runId:run.id,workflowVersionId:created.initialVersion.id,workflowVersionSemanticDigest:semantic};
  const reportB=await runtime(nodes,{required:true,trustedAttesterKeyIds:[keyA.keyId,keyB.keyId],validityMs:3600000},['record_ack']).resumeAfterHuman(principal,{runId:run.id,hosts:[hostB],humanOutcome:'approved',humanUserId:principal.userId,decider:ackDecider(),preconditions:[pre]});expect(reportB.state).toBe('completed');expect(desktop.readFile(ACK_PATH)).toBe(ACK_CONTENT);
  const hist=await support.runs.getRunHistory(principal,run.id);const b=hist.attestations.find(x=>x.stepId==='record_ack')!;expect(b.statement.runId).toBe(run.id);expect(b.statement.workflowVersionId).toBe(created.initialVersion.id);expect(b.statement.nodeId).toBe(hostB.nodeId);expect(b.statement.causalParents).toEqual([a.executionDigest]);
  const causal=verifyAttestation(hostB.attestations[0]!,{bindings:{runId:run.id,attemptId:1,stepId:'record_ack',causalParents:[a.executionDigest]},freshness:{now:support.clock.utc(),currentEpoch:TRIGGER_TEST_EPOCH,replayRegistry:new InMemoryReplayRegistry()},attesterKeyIds:[keyB.keyId]});expect(causal.ok).toBe(true);
  const wrong=verifyAttestation(hostB.attestations[0]!,{bindings:{runId:run.id,attemptId:1,stepId:'record_ack',causalParents:[sha256('wrong')]},freshness:{now:support.clock.utc(),currentEpoch:TRIGGER_TEST_EPOCH,replayRegistry:new InMemoryReplayRegistry()},attesterKeyIds:[keyB.keyId]});expect(wrong.ok).toBe(false);if(!wrong.ok)expect(wrong.failure.code).toBe('ATTESTATION_BINDING_MISMATCH');
  const evidence=new Set(hist.evidence.map(e=>e.id));for(const binding of hist.attestations)for(const ref of binding.statement.evidenceReferences as readonly string[])expect(evidence.has(ref)).toBe(true);
  expect(hist.run.state).toBe('completed');expect(hist.attempts).toHaveLength(1);expect(hist.steps.map(s=>[s.stepId,s.status])).toEqual([['collect','completed'],['approve','completed'],['record_ack','completed']]);expect(hist.invocations.map(i=>i.capability)).toEqual(['browser.observe','browser.click','browser.observe','filesystem.read','filesystem.write','filesystem.read']);expect(new Set(hist.attestations.map(x=>x.statement.nodeId))).toEqual(new Set([hostA.nodeId,hostB.nodeId]));
  const ledger=new InMemoryAttestationLedger();expect(ledger.ingest(attA,support.clock.utc()).kind).toBe('accepted');expect(ledger.ingest(attA,support.clock.utc()).kind).toBe('duplicate');const duplicateAttach=await support.runs.attachAttestation(principal,{commandId:`cmd-agent-${run.id}-att-${attA.attestationId}`,correlationId:`agent-${run.id}`},{runId:run.id,attemptNumber:1,stepId:'collect',attestation:attA,policy:{trustedAttesterKeyIds:[keyA.keyId]}});expect(duplicateAttach.executed).toBe(false);
 });
 it('fails closed before dependent side effect when precondition is absent',async()=>{
  const nodes=support.freshNodes(),keyA=generateAttesterKeyPair(),keyB=generateAttesterKeyPair();const browser=new ScriptedBrowserEnvironment([{url:FORM_URL,elements:[{elementId:'btn-submit',kind:'button',label:'Submit',state:'enabled'}]}]);const desktop=new ScriptedDesktopEnvironment({directories:['reports']});const ra=registerComputerHost({nodes,keySeed:'ig6-miss-a',platformClass:'web',capabilities:BROWSER_CAPS});const rb=registerComputerHost({nodes,keySeed:'ig6-miss-b',platformClass:'desktop',capabilities:FILE_CAPS});const A=new Capture(new WebBrowserHostAdapter({nodeId:ra.nodeId,sessionToken:ra.sessionToken,clock:()=>support.clock.utc(),capabilities:BROWSER_CAPS,attestation:{supported:true,attesterKeyId:keyA.keyId},attesterKey:keyA,environment:browser}));const B=new Capture(new DesktopHostAdapter({nodeId:rb.nodeId,sessionToken:rb.sessionToken,clock:()=>support.clock.utc(),capabilities:FILE_CAPS,attestation:{supported:true,attesterKeyId:keyB.keyId},attesterKey:keyB,environment:desktop}));const v=await createWorkflowRunOnly('ig6-missing',crossDeviceRunDoc(),nodes,principal);const A1=await runtime(nodes,{required:true,trustedAttesterKeyIds:[keyA.keyId],validityMs:300000}).executeRun(principal,{runId:v.id,hosts:[A],decider:browserDecider(),workflowInputs:{formUrl:FORM_URL}});expect(A1.state).toBe('paused');const B1=await runtime(nodes,{required:true,trustedAttesterKeyIds:[keyA.keyId,keyB.keyId],validityMs:3600000},['record_ack']).resumeAfterHuman(principal,{runId:v.id,hosts:[B],humanOutcome:'approved',humanUserId:principal.userId,decider:ackDecider()});expect(B1.state).toBe('failed');expect(B1.failure?.code).toBe('AGENT_PRECONDITION_REJECTED');expect(desktop.readFile(ACK_PATH)).toBeNull();
 });
 it('proves trust and authorization are separate dimensions',async()=>{
  const nodes=support.freshNodes(),reg=registerComputerHost({nodes,keySeed:'ig6-untrusted',platformClass:'desktop',capabilities:FILE_CAPS});const env=new ScriptedDesktopEnvironment({directories:['reports']});const host=new DesktopHostAdapter({nodeId:reg.nodeId,sessionToken:reg.sessionToken,clock:()=>support.clock.utc(),capabilities:FILE_CAPS,attestation:{supported:false,reason:'no-attester-key'},environment:env});const v=await createWorkflowRunOnly('ig6-auth',localDocument(),nodes,principal);const agent=new ComputerAgentRuntime({recorder:support.runs,nodes,workflowRepository:support.repository,clock:()=>support.clock.utc(),epoch:TRIGGER_TEST_EPOCH,policy:{maxActionsPerStep:12,maxObservationAgeMs:60000,maxRecoveryCyclesPerStep:4,safeAction:{grants:[{capability:'filesystem.read',scope:'run'}]},attestation:{required:false}},replayRegistry:new InMemoryReplayRegistry()});const r=await agent.executeRun(principal,{runId:v.id,hosts:[host],decider:ackDecider()});expect(r.failure?.code).toBe('AGENT_CAPABILITY_UNAUTHORIZED');expect(env.readFile(ACK_PATH)).toBeNull();
 });
});

async function createWorkflowRunOnly(slug:string,doc:WorkflowIrDocument,nodes:TriggerTestStack['nodes'],p:{userId:string}){const r=await inject('POST',`/organizations/${organizationId}/workflow-repository/workflows`,{slug,name:slug,description:'test',visibility:'private',content:versionContentOf(doc),protocol:{irSchemaVersion:'workflowos-workflow-ir-v1'}});expect(r.status,r.raw).toBe(201);const b=r.body as unknown as {workflow:{id:string};initialVersion:{id:string}};return createRun(b.workflow.id,b.initialVersion.id,slug);}
function crossDeviceRunDoc(){return document();}
